gui:
  showIcons: true
  theme:
    defaultFgColor:
      - white
    selectedLineBgColor:
      - '#454158'
      - reverse
    selectedRangeBgColor:
      - reverse
os:
  editCommand: 'nvim'
  openCommand: 'open {{filename}}'
